# Generated by Django 6.1.1 on 2026-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_registration_type_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
