# Generated by Django 6.1.1 on 2026-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('CORE', 'Core Member'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
