# Generated by Django 6.1.1 on 2026-10-02 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_clubmember_role_clubmember_is_president_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_president', True)), fields=('club',), name='unique_president_per_club'),
        ),
    ]
