# Generated by Django 6.1.1 on 2026-10-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_clubterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.clubterm'),
        ),
    ]
