# Generated by Django 6.1.1 on 2026-10-02 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_clubmember_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clubmember',
            name='unique_president_per_club',
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_president', True)), fields=('club',), name='unique_president_per_club_term'),
        ),
    ]
