# Generated by Django 6.1.1 on 2026-10-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_clubmember_unique_president_per_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmember',
            name='term',
        ),
        migrations.DeleteModel(
            name='ClubTerm',
        ),
    ]
