# Generated by Django 6.1.1 on 2026-10-03 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_clubmember_term_delete_clubterm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clubmember',
            name='unique_president_per_club_term',
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_president', True)), fields=('club',), name='unique_president_per_club'),
        ),
    ]
