from django.urls import path
from . import views


urlpatterns = [
    path("",views.event_list,name="event_list"),
    path(
        "create/<int:club_id>/",
        views.create_event,
        name="create_event"
    ),
    path(
      "<int:event_id>/edit/",
      views.edit_event,
      name="edit_event"
    ),
    path(
      "<int:event_id>/delete/",
      views.delete_event,
      name="delete_event"
    ),
    path(
        "<int:event_id>/",
        views.event_detail,
        name="event_detail"
    ),
    path(
      "my-registrations/",
      views.my_registrations,
      name="my_registrations"
    ),
    path(
        "club/<int:club_id>/members/",
        views.manage_members,
        name="manage_members"
    ),
    path(
        "club/<int:club_id>/members/<int:member_id>/edit/",
        views.edit_member,
        name="edit_member"
    ),
    path(
      "club-dashboard/",
      views.club_dashboard,
      name="club_dashboard"
    ),
    path(
        "clubs/<int:club_id>/members/add/<int:student_id>/",
        views.add_core_member,
        name="add_core_member"
    ),
    path(
        "club/<int:club_id>/members/<int:member_id>/remove/",
        views.remove_member,
        name="remove_member"
    ),
    path(
        "club/<int:club_id>/change-president/",
        views.change_president,
        name="change_president"
    ),
    path(
        "club/<int:club_id>/change-president/<int:student_id>/",
        views.confirm_president_change,
        name="confirm_president_change"
    ),
        path(
      "student-dashboard/",
      views.student_dashboard,
      name="student_dashboard"
    ),
    path(
      "<int:event_id>/register/",
      views.register_event,
      name="register_event"
    ),
    path(
      "club/<int:club_id>/",
      views.club_detail,
      name="club_detail"
    ),
    path(
      "club/<int:club_id>/",
      views.club_detail,
      name="club_detail"
    ),

]